<?php
if(\library\Session::get('admin')) {

    ?>
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <h4>Првка крментария</h4>
        <hr>
        <b><?=\library\Session::getFlash();?></b>
        <form method="post" action="">
            <input type="hidden" name = 'id' value="<?=$param['id']?>">
            <div class="form-group">
                <label for="massage">Коментарий</label>
                <textarea id="massage" placeholder="Название" class="form-control" name="massage"><?=$param['massage']?>
                    </textarea>
            </div>
            <div class="form-group">
                <label for="confirm">Проверен</label>
                <input id='confirm' type="text" placeholder="0/1" name="confirm" class="form-control"
                       value="<?=$param['confirm']?>">
            </div>
            <div class="form-group">
                <label for="delited">Удалена</label>
                <input id="delited" placeholder="0/1" class="form-control" type="text" name="delited"
                       value="<?=$param['delited']?>">
            </div>
            <button class="btn btn-info">Изменить</button>
        </form>
    </div>
    <?php
}
