<?php
if(\library\Session::get('admin')) {
    \library\MetaHelper::setTitle('Создание статьи');

    ?>
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>$(document).ready(function(){
            tinymce.init({ selector:'textarea' }
        )});</script>
<div class="col-sm-2"></div>
<div class="col-sm-8">
    <h1>Создать статью</h1>
    <b><?=\library\Session::getFlash();?></b>
    <form method="post" action="">
        <div class="form-group">
            <label for="cat_id">Категория новости</label>
             <select id="cat_id" class="form-control" name="cat_id" required>
                <option selected disabled>Выберите категорию</option>
                <?php \library\NewsHelper::selectListCatalog(); ?>
            </select>
            </div>
        <div class="form-group">
            <label for="post_name">Название</label>
            <input id="post_name" placeholder="Название" class="form-control" type="text" name="post_name" required>
        </div>
        <div class="form-group">
            <label for="post_text">Статья</label>
            <textarea id="post_text" name="post_text" class="form-control">

            </textarea>
        </div>
        <div class="form-group">
            <label for="tags">Теги</label>
            <input id="tags" placeholder="тег1,тег2" class="form-control" type="text" name="tags">
        </div>
        <div class="form-group">
            <label for="date">Дата</label>
            <input id="date" placeholder="" class="form-control" type="text" name="date"  value="<?=date('d-m-Y',time())
            ?>">
        </div>
        <button class="btn btn-info">Добавить</button>
    </form>
</div>
    <?php
}
