<?php
if (\library\Session::get('admin')) {
?>
<div class="center-container">
    <b><?=\library\Session::getFlash();?></b>
    <table class="pokedex-list-data table edit-list">
        <tr>
            <th>
                Ник
            </th>
            <th>
                День рождения
            </th>
            <th>
                Email
            </th>
            <th>
                Admin
            </th>
            <td>
                <button class="btn btn-info" data-toggle="modal" data-target="#myModal">Добавить</button>
            </td>
        </tr>
        <?php
        foreach ($param as $id => $user_data) {
            ?>
            <tr>
                <td>
                    <?= $user_data['nick_name'] ?>
                </td>
                <td>
                    <?= $user_data['birthday'] ?>
                </td>
                <td>
                    <?= $user_data['email'] ?>
                </td>
                <td>
                    <?= $user_data['admin'] ?>
                </td>
                <td>
                    <a href="/?route=admin/useredit&userid=<?= $user_data['id'] ?>" class="btn
btn-warning">Редактировать</a>
                </td>
                <td>
                    <a href="/?route=admin/userlist&delite=<?= $user_data['id'] ?>" class="btn btn-danger">X</a>
                </td>
            </tr>
        <?php } ?>
    </table>

    <div class="text-center">
        <ul class="pagination">
            <?= \library\PagenationRender::render("/?route=admin/userlist&offset=", 1) ?>
        </ul>
    </div>
    <?php
    }
    ?>
    <script>
        $(document).ready(function () {
            $("#birthday").mask("99-99-9999",{placeholder:"mm-dd-yyyy"})
        })
    </script>
    <!-- Форма добавления пользователя в модальном окне -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Добавить пользователя</h4>
                </div>
                <form method="post" action="">
                <div class="modal-body">
                        <div class="form-group">
                            <label for="nick_name">Ник</label>
                            <input id="nick_name" placeholder="Ник" class="form-control" type="text" name="nick_name">
                        </div>
                        <div class="form-group">
                            <label for="birthday">Возраст</label>
                            <input type="text" placeholder="mm-dd-yyyy" name="birthday" class="form-control" id="birthday">
                        </div>
                        <div class="form-group">
                            <label for="Email">Email</label>
                            <input id="Email" placeholder="Email" class="form-control" type="email" name="email">
                        </div>
                        <div class="form-group">
                            <label for="password">Пароль</label>
                            <input id="password" placeholder="Пароль" class="form-control" type="password" name="password">
                        </div>
                        <div class="form-group">
                            <label for="admin">Админ</label>
                            <input id="admin" placeholder="Admin" class="form-control" type="text" name="admin">
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    <button type="submit" class="btn btn-primary">Добавить</button>
                </div>
                </form>
            </div>
        </div>
    </div>
