<div class="col-sm-3">
    <?php
    \library\NewsHelper::menuCatalog();
    ?>
</div>
<div class="col-sm-8">
    <h4>Поиск по тегу: <?=$_GET['tag']?></h4>
    <hr>
    <?php
    foreach ($param as $k => $n_v){

    ?>
    <div class="media">
        <div class="media-left">
            <span>...</span>
        </div>
        <div class="media-body">
            <a href="/?route=news/newspost&postId=<?= $n_v['id'] ?>">
                <spam><?= $n_v['post_name'] ?></spam>
            </a>
        </div>
        <div class="media-right">
            <spam style="width: 80px;"><?= $n_v['date'] ?></spam>
        </div>
        <?php
        echo "</div>";
        }
?>
    </div>
