<?php
$pokemon_data = $param[0];
$pokemon_type = explode('/', $pokemon_data['type']);
$pokemon_weaknesses = explode('/', $pokemon_data['weaknesses']);
\library\MetaHelper::setTitle($pokemon_data['name']);
?>
<div>
    <h1 style="text-align: center"><?= $pokemon_data['name'] ?> № <?= $pokemon_data['pokemon_id'] ?></h1>
</div>
<div class="pokedex-list-data">
    <div class="col-sm-6">
        <figure>
            <img class='img-responsive' src="/webroot/img/pokedex/full/<?= $pokemon_data['pokemon_id'] ?>.png">
        </figure>
        <div class="pokemon-stats-info">
            <h3>Параметры</h3>
            <div style="margin: 20px auto; display: table;">
                <?php
                $pokemon_param = [
                    $pokemon_data['hp'],
                    $pokemon_data['attack'],
                    $pokemon_data['defense'],
                    $pokemon_data['special_attack'],
                    $pokemon_data['special_defense'],
                    $pokemon_data['speed']
                ];
                $pokemon_param_name = [
                    'Ож',
                    'Атака',
                    'Защита',
                    'Особая Атака',
                    'Особая Защита',
                    'Скорость'
                ];
                for ($i = 0; $i < 6; $i++) {
                    echo '<ul class="abil">';
                    for ($c = 0; $c < (10 - $pokemon_param[$i]); $c++) {
                        echo "<li class='clear_param'></li>";
                    }
                    for ($c = 0; $c < $pokemon_param[$i]; $c++) {
                        echo "<li class='full_param'></li>";
                    }
                    echo "<li class='type-name'>$pokemon_param_name[$i]</li>";
                    echo "</ul>";
                }
                ?>
            </div>
        </div>
    </div>
    <div class="col-sm-6 pokedex-pokemon-details-right">
        <div class="version-descriptions">

            <p class="version=-x version-x">
                <?= $pokemon_data['descriptionX'] ?>
            </p>

            <p class="version=y version-y active">
                <?= $pokemon_data['descriptionY'] ?>
            </p>

        </div>


        <h3 class="version">Версии:</h3>
        <div class="version-labels">
            <span class="version-label version-y active">ΩR</span>
            <span class="version-label version-x">αS</span>
        </div>

        <div class="color-lightblue pokemon-spec">
            <ul class="pokemon-ability-info col-sm-6">
                <li>
                    <span class="attribute-title">Рост:</span>
                    <span class="attribute-value"><?= $pokemon_data['height'] ?> m</span>
                </li>
                <li>
                    <span class="attribute-title">Вес:</span>
                    <span class="attribute-value"><?= $pokemon_data['weight'] ?> kg</span>
                </li>
                <li>
                    <span class="attribute-title">Пол:</span>
                    <span class="attribute-value"><?= $pokemon_data['gender'] ?></span></li>
            </ul>
            <ul class="pokemon-ability-info col-sm-6">
                <li>
                    <span class="attribute-title">Вид:</span>
                    <span class="attribute-value"><?= $pokemon_data['category'] ?></span>
                </li>
                <li>
                    <span class="attribute-title">Таланты:</span>
                    <span class="attribute-value"><?= $pokemon_data['abilities'] ?></span></li>
            </ul>
        </div>
        <h3 class="hchfx">Тип</h3>
        <?php
        if (count($pokemon_type) > 1) {
            foreach ($pokemon_type as $type) {
                ?>
                <div class='pokedex-pokemon-attributes'><span class='pill background-color-<?= strtolower($type)
                    ?>'><a href="#"><?= $type ?></a></span></div>
                <?php
            }
        } else {
            $type = strtolower($pokemon_type[0]);
            echo "<div class='pokedex-pokemon-attributes'>",
                "<span class='pill background-color-{$type}'><a href='#'>" . ucfirst($type) . "</a> </span>",
            "</div>";
        }
        ?>
        <div class="dtm-weaknesses">
            <h3 class="hchfx">Слабость</h3>
            <?php
            if (count($pokemon_weaknesses) > 1) {
                foreach ($pokemon_weaknesses as $weaknesses) {
                    ?>
                    <div class='pokedex-pokemon-attributes'><span
                            class='pill background-color-<?= strtolower($weaknesses)
                            ?>'><a href='#'><?= $weaknesses ?></a></span></div>
                    <?php
                }
            } else {
                $weaknesses = strtolower($pokemon_weaknesses[0]);
                echo "<div class='pokedex-pokemon-attributes'>",
                    "<span class='pill background-color-{$weaknesses}'><a href='#'>" . ucfirst($weaknesses) . "</a></span>",
                "</div>";
            }
            ?>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('.version-labels span').on('click', function () {
            if ($(this).not('.active')) {
                if ($(this).hasClass('version-y')) {
                    $('.version-descriptions .version-x').hide();
                    $('.version-descriptions .version-y').fadeIn();
                } else {
                    $('.version-descriptions .version-x').fadeIn();
                    $('.version-descriptions .version-y').hide();
                }
                $('.version-labels span.active').removeClass('active');
                $(this).addClass('active');
            }
        })
    });
</script>