<?php \library\MetaHelper::setTitle('Вход');?>
<h1 class="text-center">Войти</h1>
<b><?=\library\Session::getFlash();?></b>
<div class="col-md-3"></div>
<div class="col-md-6">
<form method="post" action="">
    <div class="form-group">
        <label for="Email">Email</label>
        <input id="Email" placeholder="Email" class="form-control" type="email" name="email">
    </div>
    <div class="form-group">
        <label for="password">Пароль</label>
        <input id="password" placeholder="Пароль" class="form-control" type="password" name="password">
    </div>
    <button class="btn btn-info">Войти</button>
</form>
</div>