<script>
    $(document).ready(function () {
        $("#birthday").mask("99/99/9999",{placeholder:"mm/dd/yyyy"})
    })


</script>
<h1>Регистрация</h1>
<b><?=\library\Session::getFlash();?></b>
<form method="post" action="">
    <input placeholder="Ник" class="form-control" type="text" name="nick_name">
    <input type="text" name="birthday" class="form-control" id="birthday">
    <input placeholder="Email" class="form-control" type="email" name="email">
    <input placeholder="Пароль" class="form-control" type="password" name="password">
    <button class="btn btn-info">Sign in</button>
</form>
