<?php \library\MetaHelper::setTitle('Регистрация');?>

<script>
    $(document).ready(function () {
        $("#birthday").mask("99-99-9999",{placeholder:"mm-dd-yyyy"})
    })
</script>
<h1 class="text-center">Регистрация</h1>
<b><?=\library\Session::getFlash();?></b>
<div class="col-md-3"></div>
<div class="col-md-6">
<form method="post" action="">
    <div class="form-group">
        <label for="nick_name">Ник</label>
        <input id="nick_name" placeholder="Ник" class="form-control" type="text" name="nick_name">
    </div>
    <div class="form-group">
        <label for="birthday">Возраст</label>
        <input type="text" placeholder="mm-dd-yyyy" name="birthday" class="form-control" id="birthday">
    </div>
    <div class="form-group">
        <label for="Email">Email</label>
        <input id="Email" placeholder="Email" class="form-control" type="email" name="email">
    </div>
    <div class="form-group">
        <label for="password">Пароль</label>
        <input id="password" placeholder="Пароль" class="form-control" type="password" name="password">
    </div>
    <button class="btn btn-info">Зарегистрироватся</button>
</form>
</div>
