<!DOCTYPE html>
<html>
<head>
    <title><?= \library\MetaHelper::getTitle(); ?></title>
    <link href="/webroot/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
    <script src="/webroot/js/jquery.min.js"></script>
    <link rel="stylesheet" href="/webroot/css/style.css">
    <link rel="stylesheet" href="/webroot/css/animate.css">

    <link rel="stylesheet" href="/webroot/bootstrap/css/bootstrap.min.css">
    <script src="/webroot/bootstrap/js/bootstrap.min.js"></script>

    <script src="/webroot/js/wow.min.js"></script>
    <script src="/webroot/js/jquery.maskedinput.min.js"></script>
    <script src="/webroot/js/jquery.twbsPagination.min.js"></script>
    <script>
        new WOW().init();

    </script>
</head>
<body>
<div class="page-wrap">
    <header class="navbar navbar-inverse">
        <ul class="nav navbar-nav container">
            <?= \library\MenuRender::render() ?>
        </ul>
    </header>

    <section class="container container-bg">
        <div class="bg-color-white">
            <div>
                <?= $content ?>
            </div>
        </div>
    </section>
    <div class="footer-divider">
        <span class="footer-notch"></span>
    </div>
</div>
<footer class="site-footer">
    <div class="container">
        &copy;
    </div>
</footer>
<?php
if(!\library\Cookie::get('subscribe')){
    \library\NewsHelper::subscribe();
}

?>
</body>
</html>