<!DOCTYPE html>
<html>
<head>
    <title><?= \library\MetaHelper::getTitle(); ?></title>
    <link rel="stylesheet" href="/webroot/css/style.css">
    <link rel="stylesheet" href="/webroot/css/animate.css">

    <link rel="stylesheet" href="/webroot/bootstrap/css/bootstrap.min.css">
    <script src="/webroot/bootstrap/js/bootstrap.min.js"></script>

    <script src="/webroot/js/wow.min.js"></script>
    <script>
        new WOW().init();
    </script>
</head>
<body>
<section class="container container-bg">

    <header>
        <nav class="navbar navbar-default">
            <a href="/">Home</a>
            <a href="/index.php?route=index/contact">Contact</a>
            <a href="/index.php?route=security/login">Login</a>
        </nav>
    </header>
    <div class="bg-color-white">
        <div>
            <?= $content ?>
        </div>
    </div>
</section>
<div class="footer-divider">
    <span class="footer-notch"></span>
</div>
<footer class="site-footer">
    <div class="container">
        &copy;
    </div>
</footer>
</body>
</html>